[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
IOSystems = "4663d367-db1f-4bef-81e7-dc1bd7f7b428"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NetworkDynamics = "22e9dc34-2a0d-11e9-0de0-8588d035468b"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
